name: test-artifact-upload

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create dummy report
        run: |
          mkdir -p allure-report
          echo "<html><body>Test</body></html>" > allure-report/index.html

      - name: Upload dummy report
        uses: actions/upload-artifact@v3
        with:
          name: Dummy-Allure-Report
          path: allure-report